server:
  port: 80

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.106.101.218:3306/app?serverTimeZone=UTC&useUnicode=true&characterEncodeing=utf-8
    username: root
    password: 60018977a
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: com.lenmain.config.UpperTableStrategy
    show-sql: true
    properties:
      hibernate:
        format_sql: true


logging:
  level:
    org.springframework.security:
      - debug
      - info
    org.springframework.web: error
    org.hibernate.SQL: debug
    org.hibernate.engine.QueryParameters: debug
    org.hibernate.engine.query.HQLQueryPlan: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
